name = "UCITools"
uuid = "6d190016-b2d6-499f-b0d4-4be18205686c"
authors = ["Patrick Staudt <patrickstaudt1@gmail.com>"]
version = "0.0.0"

[deps]
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
IndexedDataFrames = "30d8e1a9-d5cd-4a57-ad5f-8276e63f4ed5"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Plots = "91a5bcdd-55d7-5caf-9e0b-520d859cae80"
ProgressBars = "49802e3a-d2f1-5c88-81d8-b72133a6f568"
CSV = "336ed68f-0bac-5ca0-87d4-7b16caf5d00b"
Printf = "de0858da-6303-5e67-8744-51eddeeeb8d7"
Statistics = "10745b16-79ce-11e8-11f9-7d13ad32a3b2"

[compat]
julia = "1"
DataFrames = "1"
